import type { Metadata } from "next";
import {  Barlow } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header/Header";
import Footer from "@/components/footer/Footer";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };
const barlow = Barlow({
  weight: ['400', '700'], // Specify the weights you need (e.g., normal and bold)
  subsets: ['latin'], // Specify the subsets you need
  display: 'swap', // 'swap' ensures fallback text is displayed while the custom font loads
  variable: '--font-barlow', // Define a CSS variable name
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={barlow.variable}>
      <body>
        <Header  />
        {children}
        <Footer />
      </body>
    </html>
  );
}
